// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyPath(arg1) {
  return window['go']['main']['App']['CopyPath'](arg1);
}

export function CopyToDesktop(arg1) {
  return window['go']['main']['App']['CopyToDesktop'](arg1);
}

export function GetAboutMessage() {
  return window['go']['main']['App']['GetAboutMessage']();
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetPreview(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPreview'](arg1, arg2, arg3);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function ShowInExplorer(arg1) {
  return window['go']['main']['App']['ShowInExplorer'](arg1);
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}
