// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyPath(arg1:string):Promise<string>;

export function CopyToDesktop(arg1:string):Promise<string>;

export function GetAboutMessage():Promise<Record<string, string>>;

export function GetLanguage():Promise<string>;

export function GetPreview(arg1:string,arg2:number,arg3:string):Promise<main.PreviewResult>;

export function OpenFile(arg1:string):Promise<void>;

export function Search(arg1:string):Promise<Array<main.fileEntry>>;

export function SetLanguage(arg1:string):Promise<void>;

export function ShowInExplorer(arg1:string):Promise<void>;

export function StartScan(arg1:boolean):Promise<void>;
